### PR TITLE
Update xrootd 3.6 test parameters to use production repos

### PR DESCRIPTION
**Pull request by matyasselmeci**
- Add prerelease tests for xrootd for OSG 3.6
- Run osg36-xrootd tests from production since we have released it in production

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Also includes #181

**Comment by matyasselmeci** [comment]
Tests forthcoming.

**Comment by brianhlin** [comment]
Let's see if my tests against https://github.com/brianhlin/vm-test-runs/tree/update-3.6-release-tests beat yours lol

**Comment by brianhlin** [comment]
Results here: https://osg-sw-submit.chtc.wisc.edu/tests/20211203-1301/packages.html. EL8 XRootD failures are confounding.

**Comment by matyasselmeci** [comment]
I see voms failures, not xrootd failures - odd that they didn't show up for me. We should remove the voms-server bits from the test params - we use voms-proxy-direct anyway.

**Comment by brianhlin** [comment]
@matyasselmeci did you test results? If they look good, we can merge this in and I can submit another PR for my other changes that your PR didn't cover

**Comment by matyasselmeci** [comment]
Never mind, I got the same results you did.
Let's remove the voms server components from the xrootd tests and just do voms-proxy-direct.

**Comment by matyasselmeci** [comment]
https://osg-sw-submit.chtc.wisc.edu/tests/20211209-1703/packages.html (for production). We don't have xcache and osg-xrootd-standalone for EL 8 for OSG 3.5 (not upcoming) and never will, so I'll have to make a separate yaml file for osg36-xrootd.yaml for el8.

**Comment by matyasselmeci** [comment]
https://osg-sw-submit.chtc.wisc.edu/tests/20211210-1751/packages.html <- ok finally

**Comment by matyasselmeci** [comment]
This is ready for another look.

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
