### PR TITLE
Add xrootd-scitokens (needed for TPC tests)

### PR DESCRIPTION
**Pull request by matyasselmeci**
http://vdt.cs.wisc.edu/tests/20190325-1325/packages.html

### CODE REVIEW

**Comment by brianhlin** [comment]
The actual tests don't appear to run:

```
test_01_create_macaroons (osgtest.tests.test_465_xrootd_tpc.TestXrootdTPC) missing x509-scitokens-issuer-client
test_02_initate_tpc (osgtest.tests.test_465_xrootd_tpc.TestXrootdTPC) missing x509-scitokens-issuer-client
```

**Comment by matyasselmeci** [comment]
x509-scitokens-issuer-client is only in contrib (and development). We either need to ship it or change our tests not to depend on it.

**Comment by brianhlin** [comment]
I'm not sure what the intended use is for exactly. @bbockelm should we be shipping `x509-scitokens-issuer-client` in OSG release or is it more suitable for contrib?

**Comment by matyasselmeci** [comment]
The way I look at it, we have 2 choices:
1. Ship x509-issuer-client in release or
2. Modify the TPC tests to not need it

**Comment by brianhlin** [comment]
I think actually there's another option of installing `x509-scitokens-issuer-client` out of contrib in osg-test if we don't want to ship the package in release. We sorta do that with slurm/osg-development already: https://github.com/opensciencegrid/osg-test/blob/master/osgtest/tests/special_install.py#L35-L36

**Comment by matyasselmeci** [comment]
The further away we get from what our users install, the less confident I get about our tests...

**Comment by brianhlin** [comment]
Sure but the question is whether or not our users need to be issuing scitokens. Sites certainly shouldn't so maybe that happens at the VO level? And if the VO is doing it, will they do it with the `x509-scitokens-issuer-client` or some other tool? We don't understand the proposed model well enough to decide whether or not this belongs in the release so in the meantime, it makes sense to implement a workaround.

Also, I don't believe your proposed option 2 would work -- how would we test scitokens with TPC if we don't have a scitoken?

**Comment by bbockelm** [comment]
Note we support the server-side pieces, not the client-side (which is left as an exercise to the VO for now...).

While there will likely be some folks that generate tokens via `x509-scitokens-issuer`, I'd point out that it's not clear this is the primary way these will get generated.

**Comment by matyasselmeci** [comment]
We discussed this in the hallway and decided to install x509-scitokens-issuer-client out of development for the tests (like what we do for slurm). I'm not familiar with how that hack's implemented; I know I have to make changes in osg-test but are the changes for vm-test-runs good?

**Comment by brianhlin** [comment]
Yeah, I made a ticket for the osg-test changes: https://opensciencegrid.atlassian.net/browse/SOFTWARE-3649

These VMU changes look good, though.

**Pull request merged**
