### PR TITLE
Remove osg34-stashcache.yaml from default params (broken b/c SOFTWARE…

### PR DESCRIPTION
**Pull request by matyasselmeci**
…-3654)

Keep the file so we can run it manually.

### CODE REVIEW

**Comment by brianhlin** [comment]
Can we just keep it in the folder but have it all commented out? Or maybe in some `parameters-other.d/` dir? I feel like it'll be easy to forget in the root folder

**Comment by matyasselmeci** [comment]
I can do that; I put it in the root folder because apparently we did that for osg33-gums.yaml. I'd prefer commenting it out.

**Comment by matyasselmeci** [comment]
Better?

**Comment by matyasselmeci** [comment]
Having an entirely commented-out .yaml file in parameters.d kills the run with
```
Traceback (most recent call last):
  File "/osgtest/runs/run-20190409-1657/generate-dag", line 82, in <module>
    run_params = vmu.load_run_params(param_dir)
  File "/osgtest/runs/run-20190409-1657/vmu.py", line 36, in load_run_params
    if set(param_contents) == set(['platforms', 'sources', 'package_sets']):
TypeError: 'NoneType' object is not iterable
```
which is probably why we moved osg33-gums.yaml to the parent instead. I'm gonna revert that commit and push so our tests work again.

**Comment by brianhlin** [comment]
Who would write such bad code that doesn't handle empty yaml files :man_facepalming:? Hint, it's me.

**Pull request merged**
