### PR TITLE
Drop Torque tests on EL8 - it is not available

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Waiting for tests to return.

**Comment by matyasselmeci** [comment]
https://osg-sw-submit.chtc.wisc.edu/tests/20231011-1106/packages.html
does this look good?

**Comment by brianhlin** [comment]
Ya, LGTM. Though we should probably run 3.6 Torque tests but I'm afraid what you'll do if I add more jobs :D

**Comment by matyasselmeci** [comment]
> I'm afraid what you'll do if I add more jobs :D

get sick of waiting and go home at a reasonable time :)

**Pull request merged**
