### PR TITLE
Split 'All" tests into logical subsets (SOFTWARE-4289)

### PR DESCRIPTION
**Pull request by brianhlin**
Results here: https://osg-sw-submit.chtc.wisc.edu/tests/20201110-1821/results.html

1. Embarassingly we weren't testing osg-wn-client in the nightlies and our tests are failing as expected.
1. The MyProxy package set is failing to install because of a failed `rpm -q --verify`, which we weren't catching in the "All" tests. I think is due to how we decide on which packages to verify in `osg-test`

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]
LGTM. So does this cover everything that osg-tested-internal used to cover?

**Comment by brianhlin** [comment]
The only thing that's missing is `voms-server` but nobody should be running VOMS server from us

**Comment by matyasselmeci** [comment]
We need voms-server to get a voms proxy so we can test voms-proxy-init and friends (test_407_voms.py); since we've been recommending voms-proxy-init over grid-proxy-init, we should keep testing voms-proxy-init.

I don't see us explicitly testing lcmaps with voms-mapfile auth (though it might be implicit somehow), but people are still using it so we probably should.

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
Merge whenever you're ready.

**Comment by brianhlin** [comment]
Sure why not. I didn't add the EL6 tests because it's going away in a few weeks and I'm too lazy to split out the param file.

**Pull request merged**
